// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/scrabble-solve.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/dict.ts
var PATHS = {
  US: "/dict/twl06.txt",
  UK: "/dict/sowpods.txt"
};
var cache = {};
var loading = {};
function siteBaseUrl() {
  const env = globalThis.process?.env ?? {};
  return (env.PUBLIC_SITE_URL || env.SITE_URL || "https://spuk.lovable.app").replace(/\/$/, "");
}
async function loadDictionary(dict) {
  if (cache[dict]) return cache[dict];
  if (loading[dict]) return loading[dict];
  loading[dict] = (async () => {
    const url = siteBaseUrl() + PATHS[dict];
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Failed to load ${dict} dictionary (${res.status})`);
    const text = await res.text();
    const words = text.toUpperCase().split(/\r?\n/).filter((w) => w.length >= 2);
    cache[dict] = words;
    return words;
  })();
  return loading[dict];
}
var TILE_VALUES = {
  A: 1,
  B: 3,
  C: 3,
  D: 2,
  E: 1,
  F: 4,
  G: 2,
  H: 4,
  I: 1,
  J: 8,
  K: 5,
  L: 1,
  M: 3,
  N: 1,
  O: 1,
  P: 3,
  Q: 10,
  R: 1,
  S: 1,
  T: 1,
  U: 1,
  V: 4,
  W: 4,
  X: 8,
  Y: 4,
  Z: 10
};
function scoreWord(word) {
  return word.toUpperCase().split("").reduce((s, c) => s + (TILE_VALUES[c] ?? 0), 0);
}
function canMakeFromRack(word, rack) {
  const have = {};
  let blanks = 0;
  for (const c of rack.toUpperCase()) {
    if (c === "?" || c === "*") blanks++;
    else if (/[A-Z]/.test(c)) have[c] = (have[c] ?? 0) + 1;
  }
  const need = {};
  for (const c of word) need[c] = (need[c] ?? 0) + 1;
  for (const c in need) {
    const short = need[c] - (have[c] ?? 0);
    if (short > 0) {
      blanks -= short;
      if (blanks < 0) return false;
    }
  }
  return true;
}
function matchesPattern(word, pattern) {
  const p = pattern.toUpperCase();
  if (word.length !== p.length) return false;
  for (let i = 0; i < p.length; i++) {
    const ch = p[i];
    if (ch === "?" || ch === "_" || ch === ".") continue;
    if (ch !== word[i]) return false;
  }
  return true;
}

// src/lib/mcp/tools/scrabble-solve.ts
var scrabble_solve_default = defineTool({
  name: "scrabble_solve",
  title: "Scrabble solver",
  description: "Find valid Scrabble/Words With Friends plays from a rack of letters. Use '?' or '*' for blank tiles. Returns words ranked by score.",
  inputSchema: {
    rack: z.string().min(1).describe("Letters available (2-15 chars). Use '?' or '*' for blanks."),
    dictionary: z.enum(["US", "UK"]).default("US").describe("US = TWL06, UK = SOWPODS."),
    min_length: z.number().int().min(2).max(15).default(2),
    max_results: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ rack, dictionary, min_length, max_results }) => {
    const words = await loadDictionary(dictionary);
    const matches = words.filter((w) => w.length >= min_length && canMakeFromRack(w, rack)).map((word) => ({ word, score: scoreWord(word) })).sort((a, b) => b.score - a.score || b.word.length - a.word.length).slice(0, max_results);
    return {
      content: [{ type: "text", text: JSON.stringify(matches, null, 2) }],
      structuredContent: { results: matches, count: matches.length }
    };
  }
});

// src/lib/mcp/tools/crossword-match.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var crossword_match_default = defineTool2({
  name: "crossword_match",
  title: "Crossword pattern match",
  description: "Find dictionary words matching a fixed-length pattern. Use '?' (or '_' / '.') for unknown letters, e.g. 'C?T' matches CAT, COT, CUT.",
  inputSchema: {
    pattern: z2.string().min(1).max(15).describe("Pattern with '?' for unknowns."),
    dictionary: z2.enum(["US", "UK"]).default("US"),
    max_results: z2.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ pattern, dictionary, max_results }) => {
    const words = await loadDictionary(dictionary);
    const matches = words.filter((w) => matchesPattern(w, pattern)).slice(0, max_results).map((word) => ({ word, score: scoreWord(word) }));
    return {
      content: [{ type: "text", text: JSON.stringify(matches, null, 2) }],
      structuredContent: { results: matches, count: matches.length }
    };
  }
});

// src/lib/mcp/tools/word-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var word_info_default = defineTool3({
  name: "word_info",
  title: "Word info",
  description: "Look up whether a word is valid in the TWL06 (US) and SOWPODS (UK) Scrabble dictionaries and get its Scrabble tile score.",
  inputSchema: {
    word: z3.string().min(1).max(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ word }) => {
    const w = word.trim().toUpperCase();
    const [us, uk] = await Promise.all([loadDictionary("US"), loadDictionary("UK")]);
    const info = {
      word: w,
      score: scoreWord(w),
      length: w.length,
      valid_in: {
        us_twl06: us.includes(w),
        uk_sowpods: uk.includes(w)
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "lexora-mcp",
  title: "Lexora \u2014 Word Tools",
  version: "0.1.0",
  instructions: "Word game and puzzle tools from Lexora. Use `scrabble_solve` to unscramble a rack into playable words, `crossword_match` to fill fixed-length patterns with '?' placeholders, and `word_info` to validate a word and get its Scrabble score.",
  tools: [scrabble_solve_default, crossword_match_default, word_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
